// Code generated by hertz generator.

package main

import (
	"cc_blog/config"
	"fmt"
	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()
	app.Use(iris.Compression)
	customizedRegister(app)
	addr := fmt.Sprintf(":%d", config.Conf.Port)
	err := app.Listen(addr)
	if err != nil {
		panic("start server error, " + err.Error())
	}
}
